#!/bin/bash

set -e

SRC=${1:-q_analysis.txt}
DEST=${2:-q_analysis_report.md}

if [[ ! -s "$SRC" ]]; then
    echo "ERROR: Source file $SRC does not exist or is empty" >&2
    exit 1
fi

CLEAN_CONTENT=$(sed -r 's/\x1B\[[0-9;]*[mK]//g' "$SRC")

MCP_SERVERS=$(grep -E '^[[:space:]]*.*-mcp-server|^[[:space:]]*awslabs\.' <<< "$CLEAN_CONTENT" | sed 's/^[[:space:]]*//' | sort | uniq)

CRITICAL=$(grep -i "critical" <<< "$CLEAN_CONTENT" | wc -l)
HIGH=$(grep -i "high" <<< "$CLEAN_CONTENT" | wc -l)
MEDIUM=$(grep -i "medium" <<< "$CLEAN_CONTENT" | wc -l)
LOW=$(grep -i "low" <<< "$CLEAN_CONTENT" | wc -l)

{
echo "# 🧭 Amazon Q Terraform Security Analysis Report"
echo ""
echo "**Generated:** $(date '+%Y-%m-%d %H:%M:%S %Z')"
if [[ -n "$MCP_SERVERS" ]]; then
    echo "**MCP Servers Used:**"
    for srv in $MCP_SERVERS; do
        echo "- $srv"
    done
fi
echo ""
echo "---"
echo "## 📝 Summary of Findings"
echo ""
echo "- 🚨 Critical: $CRITICAL"
echo "- ⚠️ High: $HIGH"
echo "- 🟡 Medium: $MEDIUM"
echo "- 🟢 Low: $LOW"
echo ""
echo "---"
echo "## 🚨 Critical Findings"
grep -i "critical" <<< "$CLEAN_CONTENT" | sed 's/^/- 🔴 **/;s/$/**/' || echo "_No critical findings detected._"
echo ""
echo "## ⚠️ High Findings"
grep -i "high" <<< "$CLEAN_CONTENT" | sed 's/^/- 🟠 **/;s/$/**/' || echo "_No high findings detected._"
echo ""
echo "## 🟡 Medium Findings"
grep -i "medium" <<< "$CLEAN_CONTENT" | sed 's/^/- 🟡 **/;s/$/**/' || echo "_No medium findings detected._"
echo ""
echo "## 🟢 Low Findings"
grep -i "low" <<< "$CLEAN_CONTENT" | sed 's/^/- 🟢 **/;s/$/**/' || echo "_No low findings detected._"
echo ""
echo "## 💡 General Recommendations"
grep -v -i -E "(critical|high|medium|low)[^a-zA-Z]" <<< "$CLEAN_CONTENT" | sed 's/^/> /' || echo "_No general recommendations found._"
echo ""
echo "---"
echo "_Report auto-generated by Amazon Q Analysis Workflow._"
} > "$DEST"

echo "✅ Markdown report generated at $DEST"
